package gov.bms.webservices.client;

/**
 * Generated interface, do not edit.
 *
 * This stub interface was generated by weblogic
 * webservice stub gen on Thu Jul 18 02:04:29 KST 2019  
 */

public interface BmsSifOrgUserInfoViewService_V4Port extends java.rmi.Remote {
     
  /**
   * Operation Name : {http://hamoni.mogaha.go.kr/bms}isAlive   */

  public boolean isAlive() throws java.rmi.RemoteException;
    public void isAliveAsync(weblogic.wsee.async.AsyncPreCallContext apc ) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://hamoni.mogaha.go.kr/bms}getAuthedUserYNView   */

  public gov.bms.lnk.ini.vo.BmsLnkIniOrgAuthedUserYNViewResVO getAuthedUserYNView(gov.bms.lnk.ini.vo.BmsLnkIniOrgAuthedUserYNViewReqVO bmsLnkIniOrgAuthedUserYNViewReqVO) throws java.rmi.RemoteException;
    public void getAuthedUserYNViewAsync(weblogic.wsee.async.AsyncPreCallContext apc, gov.bms.lnk.ini.vo.BmsLnkIniOrgAuthedUserYNViewReqVO bmsLnkIniOrgAuthedUserYNViewReqVO) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://hamoni.mogaha.go.kr/bms}getObjAuthListView   */

  public gov.bms.lnk.ini.vo.BmsLnkIniOrgObjAuthListViewResVO getObjAuthListView(gov.bms.lnk.ini.vo.BmsLnkIniOrgObjAuthListViewReqVO bmsLnkIniOrgObjAuthListViewReqVO) throws java.rmi.RemoteException;
    public void getObjAuthListViewAsync(weblogic.wsee.async.AsyncPreCallContext apc, gov.bms.lnk.ini.vo.BmsLnkIniOrgObjAuthListViewReqVO bmsLnkIniOrgObjAuthListViewReqVO) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://hamoni.mogaha.go.kr/bms}getUserAuthInfoListView   */

  public gov.bms.lnk.ini.vo.BmsLnkIniOrgUserAuthInfoLViewResVO getUserAuthInfoListView(gov.bms.lnk.ini.vo.BmsLnkIniOrgUserAuthInfoLViewReqVO bmsLnkIniOrgUserAuthInfoLViewReqVO) throws java.rmi.RemoteException;
    public void getUserAuthInfoListViewAsync(weblogic.wsee.async.AsyncPreCallContext apc, gov.bms.lnk.ini.vo.BmsLnkIniOrgUserAuthInfoLViewReqVO bmsLnkIniOrgUserAuthInfoLViewReqVO) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://hamoni.mogaha.go.kr/bms}getUserByUIDView   */

  public gov.bms.lnk.ini.vo.BmsLnkIniOrgUserByUIDViewResVO getUserByUIDView(gov.bms.lnk.ini.vo.BmsLnkIniOrgUserByUIDViewReqVO bmsLnkIniOrgUserByUIDViewReqVO) throws java.rmi.RemoteException;
    public void getUserByUIDViewAsync(weblogic.wsee.async.AsyncPreCallContext apc, gov.bms.lnk.ini.vo.BmsLnkIniOrgUserByUIDViewReqVO bmsLnkIniOrgUserByUIDViewReqVO) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://hamoni.mogaha.go.kr/bms}getUserIdView   */

  public gov.bms.lnk.ini.vo.BmsLnkIniOrgUserIdViewResVO getUserIdView(gov.bms.lnk.ini.vo.BmsLnkIniOrgUserIdViewReqVO bmsLnkIniOrgUserIdViewReqVO) throws java.rmi.RemoteException;
    public void getUserIdViewAsync(weblogic.wsee.async.AsyncPreCallContext apc, gov.bms.lnk.ini.vo.BmsLnkIniOrgUserIdViewReqVO bmsLnkIniOrgUserIdViewReqVO) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://hamoni.mogaha.go.kr/bms}getUserModInfoListView   */

  public gov.bms.lnk.ini.vo.BmsLnkIniOrgUserInfoViewRes3VO getUserModInfoListView(gov.bms.lnk.ini.vo.BmsLnkIniOrgUserInfoViewReqVO bmsLnkIniOrgUserInfoViewReqVO) throws java.rmi.RemoteException;
    public void getUserModInfoListViewAsync(weblogic.wsee.async.AsyncPreCallContext apc, gov.bms.lnk.ini.vo.BmsLnkIniOrgUserInfoViewReqVO bmsLnkIniOrgUserInfoViewReqVO) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://hamoni.mogaha.go.kr/bms}getUserInfoView   */

  public gov.bms.lnk.ini.vo.BmsLnkIniOrgUserInfoViewResVO getUserInfoView(gov.bms.lnk.ini.vo.BmsLnkIniOrgUserInfoViewReqVO bmsLnkIniOrgUserInfoViewReqVO) throws java.rmi.RemoteException;
    public void getUserInfoViewAsync(weblogic.wsee.async.AsyncPreCallContext apc, gov.bms.lnk.ini.vo.BmsLnkIniOrgUserInfoViewReqVO bmsLnkIniOrgUserInfoViewReqVO) throws java.rmi.RemoteException ;
  
}