package gov.bms.webservices.client;

/**
 * Generated class, do not edit.
 *
 * This service interface was generated by weblogic
 * webservice stub gen on Thu Jul 18 17:19:48 KST 2019  
 */

public interface BmsSifOrgUserListService extends javax.xml.rpc.Service {

  weblogic.wsee.context.WebServiceContext context();

  weblogic.wsee.context.WebServiceContext joinContext()
       throws weblogic.wsee.context.ContextNotFoundException;
 
     

     //***********************************
     // Port Name: BmsSifOrgUserListServicePort  
     // Port Type: BmsSifOrgUserListServicePort   
     //***********************************
     
  /**
   * returns BmsSifOrgUserListServicePort port in this service 
   */
  gov.bms.webservices.client.BmsSifOrgUserListServicePort getBmsSifOrgUserListServicePort() throws javax.xml.rpc.ServiceException;

  /**
   * @deprecated Use getBmsSifOrgUserListServicePort(byte[] username, byte[] password);
   */
  gov.bms.webservices.client.BmsSifOrgUserListServicePort getBmsSifOrgUserListServicePort(String username, String password) throws javax.xml.rpc.ServiceException;

  gov.bms.webservices.client.BmsSifOrgUserListServicePort getBmsSifOrgUserListServicePort(byte[] username, byte[] password) throws javax.xml.rpc.ServiceException;
  
    
  }