package gov.bms.webservices.client;

/**
 * Generated class, do not edit.
 *
 * This service class was generated by weblogic
 * webservice stub gen on Thu Jul 18 17:19:48 KST 2019 */

public class BmsSifOrgUserListService_Impl     extends weblogic.wsee.jaxrpc.ServiceImpl
     implements gov.bms.webservices.client.BmsSifOrgUserListService {

  public BmsSifOrgUserListService_Impl() throws javax.xml.rpc.ServiceException {
    this("gov/bms/webservices/client/BmsSifOrgUserListService_saved_wsdl.wsdl", null);
  }
  
  public BmsSifOrgUserListService_Impl(String wsdlurl) throws javax.xml.rpc.ServiceException {
    this(wsdlurl, null);
  }
  
  public BmsSifOrgUserListService_Impl(String wsdlurl, weblogic.wsee.connection.transport.TransportInfo transportInfo) throws javax.xml.rpc.ServiceException {
    super(wsdlurl,
          new javax.xml.namespace.QName("http://hamoni.mogaha.go.kr/bms", "BmsSifOrgUserListService"),
          "gov/bms/webservices/client/BmsSifOrgUserListService_internaldd.xml", transportInfo);
  }
  
  //***********************************
  // Port Name: BmsSifOrgUserListServicePort 
  // Port Type: BmsSifOrgUserListServicePort 
  //***********************************

  gov.bms.webservices.client.BmsSifOrgUserListServicePort mvar_BmsSifOrgUserListServicePort;

  /**
   * returns BmsSifOrgUserListServicePort port in this service 
   */
  public gov.bms.webservices.client.BmsSifOrgUserListServicePort getBmsSifOrgUserListServicePort() 
    throws javax.xml.rpc.ServiceException
  {

    if (mvar_BmsSifOrgUserListServicePort == null) {
      mvar_BmsSifOrgUserListServicePort =
        new gov.bms.webservices.client.BmsSifOrgUserListServicePort_Stub(_getPort("BmsSifOrgUserListServicePort"), this);
    }

    if (transportInfo != null && 
        transportInfo instanceof weblogic.wsee.connection.transport.http.HttpTransportInfo) {
      ((javax.xml.rpc.Stub)mvar_BmsSifOrgUserListServicePort)._setProperty(
        "weblogic.wsee.connection.transportinfo", 
        (weblogic.wsee.connection.transport.http.HttpTransportInfo)transportInfo);
    }
    
    return mvar_BmsSifOrgUserListServicePort;
  }

  /**
   * @deprecated  Use getBmsSifOrgUserListServicePort(byte[] username, byte[] password)
   */
  public gov.bms.webservices.client.BmsSifOrgUserListServicePort getBmsSifOrgUserListServicePort(String username, String password) 
    throws javax.xml.rpc.ServiceException
  {
    if (username != null & password != null) {
      weblogic.wsee.connection.transport.http.HttpTransportInfo httpInfo = 
        new weblogic.wsee.connection.transport.http.HttpTransportInfo();
      httpInfo.setUsername(username.getBytes());
      httpInfo.setPassword(password.getBytes());
      transportInfo = httpInfo;
    }
    return getBmsSifOrgUserListServicePort();
  }

  public gov.bms.webservices.client.BmsSifOrgUserListServicePort getBmsSifOrgUserListServicePort(byte[] username, byte[] password) 
    throws javax.xml.rpc.ServiceException
  {
    if (username != null & password != null) {
      weblogic.wsee.connection.transport.http.HttpTransportInfo httpInfo = 
        new weblogic.wsee.connection.transport.http.HttpTransportInfo();
      httpInfo.setUsername(username);
      httpInfo.setPassword(password);
      transportInfo = httpInfo;
    }
    return getBmsSifOrgUserListServicePort();
  }
  
  
}