package gov.bms.srv.vo;

/**
 * Generated class, do not edit.
 *
 * This service interface was generated by weblogic
 * webservice stub gen on Thu Sep 19 10:53:50 KST 2019  
 */

public interface BmsSifOrgDeptListService_V4 extends javax.xml.rpc.Service {

  weblogic.wsee.context.WebServiceContext context();

  weblogic.wsee.context.WebServiceContext joinContext()
       throws weblogic.wsee.context.ContextNotFoundException;
 
     

     //***********************************
     // Port Name: BmsSifOrgDeptListService_V4Port  
     // Port Type: BmsSifOrgDeptListService_V4Port   
     //***********************************
     
  /**
   * returns BmsSifOrgDeptListService_V4Port port in this service 
   */
  gov.bms.srv.vo.BmsSifOrgDeptListService_V4Port getBmsSifOrgDeptListService_V4Port() throws javax.xml.rpc.ServiceException;

  /**
   * @deprecated Use getBmsSifOrgDeptListService_V4Port(byte[] username, byte[] password);
   */
  gov.bms.srv.vo.BmsSifOrgDeptListService_V4Port getBmsSifOrgDeptListService_V4Port(String username, String password) throws javax.xml.rpc.ServiceException;

  gov.bms.srv.vo.BmsSifOrgDeptListService_V4Port getBmsSifOrgDeptListService_V4Port(byte[] username, byte[] password) throws javax.xml.rpc.ServiceException;
  
    
  }