package gov.bms.srv.vo;

/**
 * Generated class, do not edit.
 *
 * This service interface was generated by weblogic
 * webservice stub gen on Thu Jul 18 02:04:31 KST 2019  
 */

public interface BmsSifOrgUserInfoViewService_V4 extends javax.xml.rpc.Service {

  weblogic.wsee.context.WebServiceContext context();

  weblogic.wsee.context.WebServiceContext joinContext()
       throws weblogic.wsee.context.ContextNotFoundException;
 
     

     //***********************************
     // Port Name: BmsSifOrgUserInfoViewService_V4Port  
     // Port Type: BmsSifOrgUserInfoViewService_V4Port   
     //***********************************
     
  /**
   * returns BmsSifOrgUserInfoViewService_V4Port port in this service 
   */
  gov.bms.srv.vo.BmsSifOrgUserInfoViewService_V4Port getBmsSifOrgUserInfoViewService_V4Port() throws javax.xml.rpc.ServiceException;

  /**
   * @deprecated Use getBmsSifOrgUserInfoViewService_V4Port(byte[] username, byte[] password);
   */
  gov.bms.srv.vo.BmsSifOrgUserInfoViewService_V4Port getBmsSifOrgUserInfoViewService_V4Port(String username, String password) throws javax.xml.rpc.ServiceException;

  gov.bms.srv.vo.BmsSifOrgUserInfoViewService_V4Port getBmsSifOrgUserInfoViewService_V4Port(byte[] username, byte[] password) throws javax.xml.rpc.ServiceException;
  
    
  }