package gov.bms.srv.vo;

/**
 * Generated class, do not edit.
 *
 * This service class was generated by weblogic
 * webservice stub gen on Wed Jul 24 10:39:35 KST 2019 */

public class BmsSifOrgUserInfoViewService_V5_Impl     extends weblogic.wsee.jaxrpc.ServiceImpl
     implements gov.bms.srv.vo.BmsSifOrgUserInfoViewService_V5 {

  public BmsSifOrgUserInfoViewService_V5_Impl() throws javax.xml.rpc.ServiceException {
    this("gov/bms/srv/vo/BmsSifOrgUserInfoViewService_V5_saved_wsdl.wsdl", null);
  }
  
  public BmsSifOrgUserInfoViewService_V5_Impl(String wsdlurl) throws javax.xml.rpc.ServiceException {
    this(wsdlurl, null);
  }
  
  public BmsSifOrgUserInfoViewService_V5_Impl(String wsdlurl, weblogic.wsee.connection.transport.TransportInfo transportInfo) throws javax.xml.rpc.ServiceException {
    super(wsdlurl,
          new javax.xml.namespace.QName("http://hamoni.mogaha.go.kr/bms", "BmsSifOrgUserInfoViewService_V5"),
          "gov/bms/srv/vo/BmsSifOrgUserInfoViewService_V5_internaldd.xml", transportInfo);
  }
  
  //***********************************
  // Port Name: BmsSifOrgUserInfoViewService_V5Port 
  // Port Type: BmsSifOrgUserInfoViewService_V5Port 
  //***********************************

  gov.bms.srv.vo.BmsSifOrgUserInfoViewService_V5Port mvar_BmsSifOrgUserInfoViewService_V5Port;

  /**
   * returns BmsSifOrgUserInfoViewService_V5Port port in this service 
   */
  public gov.bms.srv.vo.BmsSifOrgUserInfoViewService_V5Port getBmsSifOrgUserInfoViewService_V5Port() 
    throws javax.xml.rpc.ServiceException
  {

    if (mvar_BmsSifOrgUserInfoViewService_V5Port == null) {
      mvar_BmsSifOrgUserInfoViewService_V5Port =
        new gov.bms.srv.vo.BmsSifOrgUserInfoViewService_V5Port_Stub(_getPort("BmsSifOrgUserInfoViewService_V5Port"), this);
    }

    if (transportInfo != null && 
        transportInfo instanceof weblogic.wsee.connection.transport.http.HttpTransportInfo) {
      ((javax.xml.rpc.Stub)mvar_BmsSifOrgUserInfoViewService_V5Port)._setProperty(
        "weblogic.wsee.connection.transportinfo", 
        (weblogic.wsee.connection.transport.http.HttpTransportInfo)transportInfo);
    }
    
    return mvar_BmsSifOrgUserInfoViewService_V5Port;
  }

  /**
   * @deprecated  Use getBmsSifOrgUserInfoViewService_V5Port(byte[] username, byte[] password)
   */
  public gov.bms.srv.vo.BmsSifOrgUserInfoViewService_V5Port getBmsSifOrgUserInfoViewService_V5Port(String username, String password) 
    throws javax.xml.rpc.ServiceException
  {
    if (username != null & password != null) {
      weblogic.wsee.connection.transport.http.HttpTransportInfo httpInfo = 
        new weblogic.wsee.connection.transport.http.HttpTransportInfo();
      httpInfo.setUsername(username.getBytes());
      httpInfo.setPassword(password.getBytes());
      transportInfo = httpInfo;
    }
    return getBmsSifOrgUserInfoViewService_V5Port();
  }

  public gov.bms.srv.vo.BmsSifOrgUserInfoViewService_V5Port getBmsSifOrgUserInfoViewService_V5Port(byte[] username, byte[] password) 
    throws javax.xml.rpc.ServiceException
  {
    if (username != null & password != null) {
      weblogic.wsee.connection.transport.http.HttpTransportInfo httpInfo = 
        new weblogic.wsee.connection.transport.http.HttpTransportInfo();
      httpInfo.setUsername(username);
      httpInfo.setPassword(password);
      transportInfo = httpInfo;
    }
    return getBmsSifOrgUserInfoViewService_V5Port();
  }
  
  
}