package gov.bms.srv.vo;

/**
 * Generated interface, do not edit.
 *
 * This stub interface was generated by weblogic
 * webservice stub gen on Thu Sep 19 14:41:59 KST 2019  
 */

public interface BmsSifOrgDeptListService_V3Port extends java.rmi.Remote {
     
  /**
   * Operation Name : {http://hamoni.mogaha.go.kr/bms}isAlive   */

  public boolean isAlive() throws java.rmi.RemoteException;
    public void isAliveAsync(weblogic.wsee.async.AsyncPreCallContext apc ) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://hamoni.mogaha.go.kr/bms}getAllDeptListView   */

  public gov.bms.lnk.ini.vo.BmsLnkIniOrgAllDeptLViewRes2VO getAllDeptListView(gov.bms.lnk.ini.vo.BmsLnkIniOrgAllDeptLViewReqVO bmsLnkIniOrgAllDeptLViewReqVO) throws java.rmi.RemoteException;
    public void getAllDeptListViewAsync(weblogic.wsee.async.AsyncPreCallContext apc, gov.bms.lnk.ini.vo.BmsLnkIniOrgAllDeptLViewReqVO bmsLnkIniOrgAllDeptLViewReqVO) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://hamoni.mogaha.go.kr/bms}getAllDeptListViewLite   */

  public gov.bms.lnk.ini.vo.BmsLnkIniOrgAllDeptLViewRes2VO getAllDeptListViewLite(gov.bms.lnk.ini.vo.BmsLnkIniOrgAllDeptLViewReqVO bmsLnkIniOrgAllDeptLViewReqVO) throws java.rmi.RemoteException;
    public void getAllDeptListViewLiteAsync(weblogic.wsee.async.AsyncPreCallContext apc, gov.bms.lnk.ini.vo.BmsLnkIniOrgAllDeptLViewReqVO bmsLnkIniOrgAllDeptLViewReqVO) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://hamoni.mogaha.go.kr/bms}getFirstDeptListView   */

  public gov.bms.lnk.ini.vo.BmsLnkIniOrgFirstDeptLViewRes2VO getFirstDeptListView(gov.bms.lnk.ini.vo.BmsLnkIniOrgFirstDeptLViewReqVO bmsLnkIniOrgFirstDeptLViewReqVO) throws java.rmi.RemoteException;
    public void getFirstDeptListViewAsync(weblogic.wsee.async.AsyncPreCallContext apc, gov.bms.lnk.ini.vo.BmsLnkIniOrgFirstDeptLViewReqVO bmsLnkIniOrgFirstDeptLViewReqVO) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://hamoni.mogaha.go.kr/bms}getSubDeptListView   */

  public gov.bms.lnk.ini.vo.BmsLnkIniOrgSubDeptLViewRes2VO getSubDeptListView(gov.bms.lnk.ini.vo.BmsLnkIniOrgSubDeptLViewReqVO bmsLnkIniOrgSubDeptLViewReqVO) throws java.rmi.RemoteException;
    public void getSubDeptListViewAsync(weblogic.wsee.async.AsyncPreCallContext apc, gov.bms.lnk.ini.vo.BmsLnkIniOrgSubDeptLViewReqVO bmsLnkIniOrgSubDeptLViewReqVO) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://hamoni.mogaha.go.kr/bms}getByDeptUserInfoListView   */

  public gov.bms.lnk.ini.vo.BmsLnkIniOrgUserInfoViewResVO getByDeptUserInfoListView(gov.bms.lnk.ini.vo.BmsLnkIniOrgUserInfoViewReqVO bmsLnkIniOrgUserInfoViewReqVO) throws java.rmi.RemoteException;
    public void getByDeptUserInfoListViewAsync(weblogic.wsee.async.AsyncPreCallContext apc, gov.bms.lnk.ini.vo.BmsLnkIniOrgUserInfoViewReqVO bmsLnkIniOrgUserInfoViewReqVO) throws java.rmi.RemoteException ;
  
}